services:

  mysql:
    image: mysql:8.0
    container_name: mysql_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tech_library
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    command: --default-authentication-plugin=mysql_native_password

    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
